
server:
  port: 2333
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/robot_wali_dev?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: guakun22Pwd